mbed_cloud_client_resource.cpp
mbed_cloud_client_resource.h
memory_tests.cpp
resource.cpp
simple-mbed-cloud-client.cpp
simple-mbed-cloud-client.h

Merging a bunch of work that I did for the original Simple Cloud Client into this project:
* Add on_registered / on_unregistered callbacks and remove unnecessary printf() statements from client.
* Create better put/post/notification callbacks, which actually give some useful information rather than leaking internal structures into the user application.
* PUT handlers now get the new value of the resource.
* POST handlers now receive the decoded body of the POST request.
* Notification handlers can get a string version of the notification.
* All callbacks also receive the resource as parameter, so you don't need to clobber global scope.
I've updated the example app [here](https://gist.github.com/janjongboom/9923191ab107acddfd79e10c05ca4d1f) - as I could not find it on GitHub.
Note that I …

Add callbacks, better put/post notifications

---

simple-mbed-cloud-client.cpp
simple-mbed-cloud-client.h

Added an explicit call to fs->mount() in the init() function.
FileSystem does not require a block device to be passed to it:
https://github.com/ARMmbed/mbed-os-example-filesystem/blob/master/main.cpp#L39
If you do not pass a block device to the constructor, it will not automatically do a mount. By calling mount() explicitly, we support constructors without this block device.
Tested with LittleFileSystem and FATFileSystem.
Without this fix, if you do not pass a block device to your file system constructor, the FCC looks for an unmounted file system, thus your credentials will be written over and you will receive a new device identity.

Mount filesystem if wasn't done in the application

---

README.md
TESTS/host_tests/sdk_host_tests.py
TESTS/simple/connect/main.cpp
mbed-cloud-client.lib
simple-mbed-cloud-client.h

Note: WiP, not ready for merge, various decisions need input.
**What**
A simple Greentea test case for Simple Cloud Client, that tests that the platform is able to register to Mbed Cloud, and uses the Python SDK to confirm that from Mbed Cloud.
**Why**
This can be used by partners and developers as they integrate their platform to be compatible with Mbed Cloud.
**Challenges**
The biggest challenge is to standardize the configurations for each platform. At a bare minimum, each platform will have different:
- Storage
- Connectivity
- SOTP regions
In the future, we will want to test Update, which will also include custom memory definitions for app-starts, potentially larger stack sizes, etc.
Currently, this is being solved by having a set of custom mbed_app.json parameters that must be …

Simple Cloud Client Tests

---

.gitignore
README.md
TESTS/host_tests/sdk_host_tests.py
TESTS/simple/connect/main.cpp
simple-mbed-cloud-client.cpp

Mbed OS 5.10 includes default network interfaces and storage block device drivers for platforms.
This PR introduces changes to:
- Update test configuration to use the default configuration
- Documentation & rebranding updates
Note, continues to be based on (MCC) Pelion Client library v1.4.0
This PR precedes the SMCC application here:
cc @dhwalters423 @bridadan @janjongboom
Please review asap - we aim to merge this today

Default network and storage configuration

---

README.md
TESTS/host_tests/sdk_host_tests.py
TESTS/simple/connect/main.cpp

Tests the creation, GET and PUT operations of LwM2M resources on the device using the Python SDK Connect API.
Creates 2 LwM2M resources on the device and performs the following functionality:
- Reads the initial value of /5000/0/1 from the Python SDK
- Update the value of /5000/0/1 and observe change from Python SDK
- Reads the initial value of /5000/0/2, increments it by 5, PUTs the new incremented value to /5000/0/2, and verifies change was made to device.
This is ready for merge.
**Future enhancements**
Things planned for the future: 
Splitting this to 4 different tests (CONNECT, CONSISTENT ID, GET, PUT)
POST test verifying callback functionality on device.

LwM2M GET+PUT tests

---

README.md
TESTS/host_tests/sdk_host_tests.py
TESTS/simple/connect/main.cpp

This is the agreed upon approach with @screamerbg for TechCon release.
Separates out test cases within a single main.cpp test.
Tested and confirmed to work with: K64F and NUCLEO F429ZI.
Output:
```
mbedgt: test suite report:
+----------+---------------+-----------------------------------------------+--------+--------------------+-------------+
| target   | platform_name | test suite                                    | result | elapsed_time (sec) | copy_method |
+----------+---------------+-----------------------------------------------+--------+--------------------+-------------+
| K64F-ARM | K64F          | simple-mbed-cloud-client-tests-simple-connect | OK     | 119.06             | default     |
+----------+---------------+-----------------------------------------------+--------+------ …
```

Separate test cases

---

README.md
TESTS/simple/connect/main.cpp

Mbed OS 5.10 abstracts details on network interfaces, making applications easier to work multiple connectivities types.
This is a simplification of the tests to use the default network interface. Specific changes may need to come from `mbed_app.json` as already being done (e.g. WIFI SSID, PASS, etc).
@bridadan @dhwalters423

Simplify network setup

---

README.md
TESTS/host_tests/sdk_host_tests.py
TESTS/simple/connect/main.cpp

* [device] use logger() function which adds 10ms delay (in 10x 1ms pieces) before and after printing out
* [device] use while(1) loops when fetching {{key:value}} pairs from host
* [device] provide manifest which tests are available, thus allow tracking of skipped tests
* [device] overall tests success
* [host] use class variables instead of globals
* [host] use SDKTests.send_safe() function instead of send_kv() to override behavior and help with debugging

Changes to SMCC tests

---

TESTS/simple/connect/main.cpp

This is required to let some platforms and connectivity to work, eg C030 + Cellular
@janjongboom @screamerbg

Increase test timeout for slow networks

---

TESTS/dev_mgmt/connect/main.cpp

Also renamed the test to "dev_mgmt". Previous it was called "simple", which is confusing.

Pelion tests fixes. Race conditions, timeouts, rawserial etc

---

TESTS/host_tests/sdk_host_tests.py

Mbed CLI 1.8.3 displays extra config information when using `mbed config`
This PR introduces an enhancement to parse the CLOUD_SDK_API_KEY config in a more robust way, regardless of other config options.
FYI @screamerbg @janjongboom

Fix extra config introduced in Mbed CLI 1.8.3 #44

---

README.md
TESTS/dev_mgmt/connect/main.cpp
TESTS/dev_mgmt/update/main.cpp
TESTS/host_tests/sdk_host_tests.py
update_ui_example.cpp

This PR introduces Firmware Update tests for Pelion DM, including documentation about the test cases and prerequisites.
| **Test case** | **Description** |
| ------------- | ------------- |
| `Connect to Network` | Tests the connection to the network via network interface. |
| `Format Storage` | Tests that a successful storage format occurs and storage is configured correctly. |
| `Simple MCC Initialization` | Verifies that SPDMC can be initialized with the given network, storage, and filesystem configuration. This is where the FCU and KCM configuration is written to storage and the Root of Trust is written to SOTP. |
| `Pelion DM Bootstrap & Register` | Bootstraps the device and registers it for first time with Pelion Device Management. |
| `Pelion DM Directory` | Verifies that a …

Feature: Firmware Update tests

---

TESTS/dev_mgmt/connect/main.cpp
TESTS/dev_mgmt/update/main.cpp

According to K64F & NUMAKER_IOT_M487 platform through WiFi connection, default time out 30 seconds is not enough, so suggest to adjust as 60 seconds.
Details of test log are attached for your reference.
[k64f_smcc_armcc.txt](https://github.com/ARMmbed/simple-mbed-cloud-client/files/2619412/k64f_smcc_armcc.txt)
[Uploading m487_smcc_armcc.txt…]()

Enlarge timeout of client register

---

TESTS/basic/net-single/main.cpp
TESTS/basic/net-threaded/main.cpp
TESTS/basic/stress-net-fs/main.cpp
TESTS/dev_mgmt/connect/main.cpp
TESTS/dev_mgmt/update/main.cpp
TESTS/host_tests/sdk_host_tests.py

This PR aims to improve the following aspects of Device Management tests for SPDMC:
* Use `wait_ms()` instead of `while()` loop, which was previously used to prevent strange behavior with some Targets in TICKLESS mode.
* Speed-up Pelion DM registration and PDM device directory test cases by querying on every 100ms instead of previously hardcoded 5 seconds wait. Also increase the timeout for these test cases to 10 seconds.
* Prevent boot loop due to Mbed OS crash by limiting the times the host test python script will respond (currently up to 5 `{{device_ready}}` messages)
* Improve the output of both Connect and Update test suites for better readability when using verbose mode `mbed test ... -v`. See example 1 below.
* Correctly report the number of successful test runs for a routine if …

Device Management tests improvements

---

TESTS/dev_mgmt/update/main.cpp

Some block devices will return an error when trying to do an in-place overwrite like this (such as MX25R3235F). Instead, actually do what the comments say and erase the smallest size we can to invalidate the update image checksum.

Can't rely on all BlockDevices supporting in-place overwrite

---

TESTS/host_tests/sdk_host_tests.py

Fixes this trace back :
```
[1550238799.45][HTST][INF] ==== Traceback start ====
Traceback (most recent call last):
File "/.virt/local/lib/python2.7/site-packages/mbed_os_tools/test/host_tests_runner/host_test_default.py", line 422, in run_test
callbacks[key](key, value, timestamp)
File "/pelion-enablement/simple-mbed-cloud-client/TESTS/host_tests/sdk_host_tests.py", line 158, in _callback_verify_lwm2m_put
async_response = self.connectApi.set_resource_value_async(self.deviceID, value, updated_value)
File "/.virt/local/lib/python2.7/site-packages/mbed_cloud/decorators.py", line 33, in wrapped_f
return fn(*args, **kwargs)
File "/.virt/local/lib/python2.7/site-packages/mbed_cloud/connect/connect.py", line 356, in set_resource_value_async
payload_b64 = …
```

fixes the type of the value sent to the connect API.

---

TESTS/basic/fs-single/main.cpp
TESTS/basic/fs-threaded/main.cpp
TESTS/basic/net-single/main.cpp
TESTS/basic/net-threaded/main.cpp
TESTS/basic/stress-net-fs/main.cpp
TESTS/dev_mgmt/connect/main.cpp
TESTS/dev_mgmt/update/main.cpp

Some target such as the NUCLEO_L476RG has only 1 controllable led that conflict with SPI's CLK on Arduino's pin D13.
If set, this flag disables the led_thread.
Alternatively, this option could be provided as a proper config in mbed_lib.json.
Would that be a prefered solution to the solution in this PR ?

add support for the "NO_LED" flag that disable the heartbeat thread

---

TESTS/basic/fs-single/main.cpp
TESTS/basic/fs-threaded/main.cpp
TESTS/basic/net-single/main.cpp
TESTS/basic/net-threaded/main.cpp
TESTS/basic/stress-net-fs/main.cpp
TESTS/dev_mgmt/connect/main.cpp
TESTS/dev_mgmt/update/main.cpp

Putting LED1 and LED2 component when MBED_CONF_APP_NO_LED macro is not defined.
In original code, when MBED_CONF_APP_NO_LED is not defined, LED is not blinking; when MBED_CONF_APP_NO_LED is defined, LED is blinking, which is weird.

fix NO_LED defines, allowing devices with no LEDs to work

---

TESTS/dev_mgmt/connect/main.cpp
TESTS/dev_mgmt/update/main.cpp
simple-mbed-cloud-client/simple-mbed-cloud-client.cpp
simple-mbed-cloud-client/simple-mbed-cloud-client.h
storage-helper/storage-helper.h

Fix to avoid SimpleMbedCloudClient from re-initialising filesystem storage
As of MCC 2.1.0, arm_uc_blockdevice is no longer referenced from MCC, and is therefore pointless to keep in SMCC.
As such, SMCC only tracks the blockdevice backing the filesystem now, not the one backing both filesystem and upgrade storage. That solves the issue of the internal remount logic remounting the filesystem onto the full blockdevice, instead of the potentially smaller slicingblockdevice having been assigned to the filesystem earlier.

Avoid re-mounting filesystem on different BD

---

mbed_lib.json

Based on the tip from https://github.com/ARMmbed/pelion-ready-example/pull/21. This saves 15K flash and 0.5K static RAM (and also some dynamic RAM, but that could have been a fluke).
Before:
```
Base (with memory tracing enabled)
===================================
Total Static RAM memory (data + bss): 78176 bytes
Total Flash memory (text + data): 426913 bytes
Heap size: 43701 / 117384 bytes (max: 50738 bytes)
```
After:
```
Disable STL
===========
Total Static RAM memory (data + bss): 77672 bytes
Total Flash memory (text + data): 411903 bytes
Heap size: 43257 / 117384 bytes (max: 50286 bytes)
```
Tested on K64F but would be good to verify in test farm.
@screamerbg

Disable C++ STL

---

mbed-cloud-client.lib
mbed_lib.json

Note that this requires the application config to define `"mbed-cloud-client.external-sst-support"    : null` to re-enable the "legacy" nvstore SOTP support.

Update to PDMC 3.0.0

---

simple-mbed-cloud-client/simple-mbed-cloud-client.cpp

The hard fault was caused by an off-by-one error in the SPDMC destructor.
So for an example, when 3 resources were pushed to the list, 4 would be deleted.

Fix SPDMC desctructor HardFault.

---

README.md
TESTS/host_tests/sdk_host_tests.py

- Check that mbed-cloud-sdk >= 2.0.6 which introduced support for integer
resource value set.
- Check that "mbed dm init..." has been ran. This is detected from
modified ".manifest_tool.json"

Detect common user errors runtime.

---

TESTS/COMMON/download_test.cpp

I have observed that in download test, sometimes server returns HTTP Bad Request due to double spaces in GET request format. I tried multiple times with single space and did not get any error. It is suggested to remove the extra space as normally there's only one space in GET request format.
@MarceloSalazar

Remove extra space from GET request

---

TESTS/dev_mgmt/connect/main.cpp
TESTS/dev_mgmt/update/main.cpp

The Bootstrap & Reg time is over 60 seconds on NUMAKER_PFM_NUC472 platform.
SMCC test log shows NUC472 Bootstrap & Reg time 62 seconds.
So enlarge time out from 60 seconds as 65 seconds.
[pfm_nuc472_dev_mgmt.log](https://github.com/ARMmbed/simple-mbed-cloud-client/files/3080138/pfm_nuc472_dev_mgmt.log)
Snippet of log as:
`[1555327983.63][CONN][RXD] >>> Running case #5: 'Pelion Bootstrap & Reg.'...
[1555327983.63][CONN][INF] found KV pair in stream: {{__testcase_start;Pelion Bootstrap & Reg.}}, queued...
[1555328045.13][CONN][RXD] [INFO] Connected to Pelion Device Management. Device ID: 016a20c6369000000000000100100371
[1555328045.32][CONN][RXD] [INFO] Device successfully registered to Pelion DM.`
Attached SMCC test log file for reference.

Enlarge Bootstrap & Reg timeout for NUMAKER_PFM_NUC472 platform

---

TESTS/dev_mgmt/connect/main.cpp
TESTS/dev_mgmt/update/main.cpp
mbed_lib.json
simple-mbed-cloud-client/pal_config_MbedOS.h
simple-mbed-cloud-client/simple-mbed-cloud-client.cpp
simple-mbed-cloud-client/simple-mbed-cloud-client.h

This pull request adds support for kvstore to simple cloud client.  I've tested this on K64F and it is able to connect and register to Pelion.  
I've updated the connect and tests.  If mbed trace is disabled they all pass.  With mbed trace on, some tests seems to get lost in too much serial data and they report as skipped. 
Next steps:
- Get the connect test working - done
- Get the update test working - done
- Test with more boards
- Clean up the test case names, etc to fit kvstore instead of traditional file system.
- Maybe switch all boards to use kvstore and remove all SOTP storage related code.

add support for kvstore
